### ISSUE TITLE
Add missing methods to UIO companion object

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#1]
`UIO` companion object should have all the methods from bifunctor companion object where it makes sense to return `UIO`. They can just forward to the main ones. Please try to preserve the same ordering

**Comment by Avasil** [comment]
How about this one @aleksandarskrbic for a start?

It's a copy paste with a little bit of thinking so not very interesting but should make you familiar with a process and how code is organized. :)

The task is to take all public methods from `BIO` companion object (`object BIO { ... }`) and add it to `object UIO`. They should return `UIO` instead of `BIO` as well. Not always it will make sense, e.g. `UIO.raiseError`. If you have any doubts, just ask. You can always just copy everything and we will remove redundant stuff in the PR.

The process to make a PR is like this:
- Fork a repository (click on github)
- Clone your forked repository (something like github.com/aleksandarskrbic/monix-bio )
- Create a new branch there
- Implement the changes
- Commit and push your changes
- When you enter monix-bio repo (either your fork or the main one) you will see a button to create a pull request
- Submit a PR, you can write "fixes #issueNumber" in the description to automatically close the corresponding issue.

I also wrote a little bit more context below, please let me know if anything is confusing and have any questions!

The main type exposed by library is called `BIO`. 
It has two type parameters, i.e. `E` and `A`.

`BIO[E, A]` describes an effect that after running will either produce a successful value of type `A`, produce an error of type `E`, fail with unexpected error, or never terminate. 

It has a lot of methods to support concurrency, resource safety, cancelation, error handling etc. It is also lazy - creating a `BIO[E, A]` doesn't invoke any actions yet - it needs to be run first. It is essential for referential transparency which you will see coming up a lot as you learn FP. :D Purely functional program usually just compose type like `BIO[E, A]` and run it once at the very end.

These types are often called "IO Monad" but it usually has a shape of `IO[A]`. The difference between `BIO` and `IO` is that `BIO` introduces this `E` parameter which allows to fail with error types other than `Throwable`. So if a method returns `IO[A]` the caller doesn't really know what kind of an error can happen and it can be useful information, for instance we would like to return a domain error which can be handled by the caller according to the business logic. It can be solved with `IO[Either[E, A]]` but ergonomics are much worse and there is a performance penalty in some cases.

`BIO[E, A]` has two channels of errors:
a) The errors of type `E`. These are usually expected errors that can be recovered from.
b) `Throwable`. On JVM there can be always an error but most of the time we don't care about it and can't really handle it. We treat them as "fatal" errors or defects and let them kill our task (IO/BIO). They skip almost all error handlers for `E` errors.

We provide two type aliases:
- `BIO[Throwable, A]` called `Task` - here we lose the benefits from typed errors but it's sometimes more convenient if we don't want it or interop with untrusted code
- `BIO[Nothing, A]` called `UIO` - this one is pretty cool. `Nothing` means that this `BIO` can't fail because there is no value of type `Nothing`. With normal `IO[A]`, we can call a method like `onErrorHandle`, handle all the errors but the return type is still `IO[A]` even if it can't really fail anymore. With `BIO[E, A]` we can return `UIO[A]` to indicate that everything is handled and we don't have to worry about it. Of course there is still a possibility of unexpected errors but it is something that we don't care about most of the time (most codebases have just a single catch-all error handler to convert them to 500 response at the edge of the app).

**Comment by aleksandarskrbic** [comment]
Thanks for helping, I will take this one!
