### ISSUE TITLE
Implement flatMapError

### ISSUE THREAD

**Issue by Executioner1939** [monix/monix-bio#107]
I see `ZIO` has `flatMapError` which could be useful, I wonder if we should add it as well? I think it could be implemented with `flipWith` but there may be a more efficient way to do it.

**Comment by Avasil** [comment]
On a quick glance it looks similar to `def onErrorHandleWith[E1, B >: A](f: E => BIO[E1, B]): BIO[E1, B]`
Are there any use cases that are better to solve with `flatMapError`?

**Comment by Executioner1939** [comment]
Hi Avasil, as discussed this is a niche method and we can park it's implementation until there is enough demand.
