### ISSUE TITLE
Implement fromOption and fromOptionF

### ISSUE THREAD

**Issue by Executioner1939** [monix/monix-bio#108]
Hi Avasil,

This is a ticket for the above discussed operators :-).

I was thinking:

```scala
final def fromOption[E, A](opt: Option[A], ifEmpty: => E): BIO[E, A]
```
and 

```scala
final def fromOptionF[E1 >: E, A](opt: BIO[E, Option[A]], ifEmpty: => E1): BIO[E1, A]
```

You also mentioned a variant that returns `BIO[Unit, A]`, could you elaborate on that please :-).

**Comment by Executioner1939** [comment]
I am gonna make a PR for these today so long

**Comment by Avasil** [comment]
> You also mentioned a variant that returns BIO[Unit, A], could you elaborate on that please :-).

`BIO[Unit, A]` is isomorphic to `Option[A]` - there is only one possible cause of error and it has no specific information

> final def fromOption[E, A](opt: Option[A], ifEmpty: => E): BIO[E, A]

I feel like we should do it in similar way to `Option.fold`, that is (ifEmpty : => E)(a: Option[A]) but I'm not 100% sure yet, I have to check other libraries

> final def fromOptionF[E1 >: E, A](opt: BIO[E, Option[A]], ifEmpty: => E1): BIO[E1, A]

I don't think we use `F` postfix anywhere but we do use `With` in methods like `redeemWith` so perhaps `fromOptionWith` ? Although it usually takes a function so I'm open to ideas

**Comment by Executioner1939** [comment]
> I don't think we use F postfix anywhere but we do use With in methods like redeemWith so perhaps fromOptionWith ? Although it usually takes a function so I'm open to ideas

The `F` postfix I got from cats `EitherT`, we can change it to `With`, at least then it's consistent except for the fact that it's not receiving a function in this case, but rather a `BIO[E, Option[A]]`

> I feel like we should do it in similar way to Option.fold, that is (ifEmpty : => E)(a: Option[A])
In my own opinion having the fallback as the last parameter list reads better, for example:

First lookup a user and if it doesn't exist then use the provided fallback
`BIO.fromOptionWith(findUserById)(NotFound("Unable to find the specified User by Id"))`

If the standard is to have the fallback first then we must do that as following standards are important.

**Comment by Avasil** [comment]
> Could this not be implemented on UIO?

No, `UIO` uses `Nothing` (0 possible values) and here we have `Unit` (1 possible value)

**Comment by Executioner1939** [comment]
Okay, that makes sense. If we can come up with all the names and type signatures I can implement all of them tonight.

**Comment by Avasil** [comment]
> In my own opinion having the fallback as the last parameter list reads better, for example:
First lookup a user and if it doesn't exist then use the provided fallback
`BIO.fromOptionWith(findUserById)(NotFound("Unable to find the specified User by Id"))`

Unfortunately it is not always possible, let's say:

```scala
def fromOption1[E, A](opt: Option[A])(ifEmpty :=> E): BIO[E, A] = ???
def fromOption1[A](opt: Option[A]): BIO[E, A] = ???

def test1 = fromOption1(Some(2)(2) // ambiguous reference to overloaded definition
```
On the other hand:

```scala
def fromOption2[E, A](ifEmpty :=> E)(opt: Option[A]): BIO[E, A] = ???
def fromOption2[A](opt: Option[A]): BIO[E, A] = ???

def test1 = fromOption2(2)(Some(2)) // compiles fine
```

And that's how `Task.fromEither` is implemented in Monix

About effectful variant I honestly don't know:
- `EitherT.fromOptionF` has `(F[Option], E])` (error second, not curried)
- `redeem` has `(E => B, A => B)` (error first, not curried)
- `Option.fold` has `(ifEmpty)(f)` (error first, curried)

but maybe I'm missing a pattern. :P I suppose if the use case for `fromOptionF` comes from `EitherT` then it might be best to just follow it.

Regarding the name, I was thinking about `fromOptionEval` - there isn't anything like it in `Task` but it is used a lot in `Observable`

**Comment by Executioner1939** [comment]
> Regarding the name, I was thinking about fromOptionEval - there isn't anything like it in Task but it is used a lot in Observable

I was also considering `Eval` as it's used in Observable, but I didn't find it's usage in `monix.eval.Task`. If you're okay with `Eval` then I'll implement:

```scala
final def fromOptionEval[E1 >: E, A](opt: BIO[E, Option[A]], ifEmpty: => E1): BIO[E1, A]
```
and
```scala
final def fromOption[E1 >: E, A](opt: Option[A], ifEmpty: => E1): BIO[E1, A]
```
I don't mind doing error first and curried if that's what you prefer :-).

**Comment by Avasil** [comment]
`fromOptionEval` is fine but I would like to have two `fromOption` variants as described above:

```
def fromOption[E, A](ifEmpty :=> E)(opt: Option[A]): BIO[E, A] = ???
def fromOption[A](opt: Option[A]): BIO[Nothing, A] = ???
```

to infer properly

**Comment by Executioner1939** [comment]
Awesome, will do :-)

**Comment by Avasil** [comment]
I have just noticed there is 
```scala
def fromOption[A](oa: Option[A], ifEmpty: => E): F[A] 
```

in `ApplicativeError` in Cats so now I grow to your initial proposal, uhh 😅

**Comment by Executioner1939** [comment]
@Avasil oh kwl :-). So that is where it comes from :-).
