### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by paualarco** [monix/monix-bio#115]

**Comment by paualarco** [comment]
I would be happy to help with that, since I've done it before :)
Noticed that for travis there is only tests running with `jdk11`. Should `jdk8` be included as well?

**Comment by Avasil** [comment]
Sure, go ahead :)

> Noticed that for travis there is only tests running with jdk11. Should jdk8 be included as well?

Maybe for 1 version as a sanity check, I recall only one case when something was working on jdk8 but on jdk11 but it wasn't caught by unit tests anyway
