### ISSUE TITLE
Add missing methods to Task companion object

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#2]
`Task ` companion object should have all the methods from bifunctor companion object where it makes sense to return `Task `. They can just forward to the main ones. Please try to preserve the same ordering

**Comment by aleksandarskrbic** [comment]
I will take this one :D

**Comment by Avasil** [comment]
@aleksandarskrbic 
Anything I can help with?
I'm closing on 0.1.0 (would like to release it in 1-2 weeks) and would like to include it there

**Comment by aleksandarskrbic** [comment]
@Avasil Hi, I was very busy so I didn't have much time to work on this. I will submit PR in next few hours :D. For now, I don't need help

**Comment by Avasil** [comment]
Solved in #84
