### ISSUE TITLE
Add Bracket instance instead of MonadError

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#4]
I think it should be possible to use [Bracket[E, A]](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Bracket.scala) instead of `MonadError` in [CatsBaseForTask](https://github.com/monix/monix-bio/blob/master/core/shared/src/main/scala/monix/bio/instances/CatsBaseForTask.scala). We already have the functions in [CatsConcurrentForTask](https://github.com/monix/monix-bio/blob/master/core/shared/src/main/scala/monix/bio/instances/CatsConcurrentForTask.scala) so it should be relatively straightforward

It might make sense to test the instance in `BaseTypeClassLawsForTaskSuite` with something different than Throwable if possible

**Comment by pk044** [comment]
i can take this :+1:

**Comment by pk044** [comment]
it seems like i'll be too busy in the following few weeks - so it's free to take if anyone is up for solving this issue

**Comment by Avasil** [comment]
Nevermind, I feel like not all types line up so let's leave it as is
