### ISSUE TITLE
How to call untyped errors

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#40]
There are two channels of errors in Bifunctor implementations:
- "Typed" errors which are part of the type signature and most error handling operators should work on this kind of errors
- Untyped / fatal / defects / unrecoverable errors which are hidden from the signature and generally these are exceptions like `RejectedExecutionException` and everything that we don't care about in the signature.

I'm not sure how to call the latter, right now I use "fatal" which is kind of accurate but I'm worried about confusion with `scala.util.control.NonFatal` and really fatal errors like `OutOfMemoryError`

**Comment by xplosunn** [comment]
I suggest `Unexpected`.

**Comment by Avasil** [comment]
> I suggest `Unexpected`.

I think `Unexpected` is good in docs but I've forgotten to mention that I'm looking for something to use in method names, i.e. `raiseFatalError`, `redeemFatalWith` etc. Although if we stay with `Cause` and do `redeemCauseWith` (similar to ZIO naming with `foldCauseM`) for cases which handle both cases and `raiseUnexpectedError`, `onUnexpectedError` it might be decent. Thanks for suggestion!

**Comment by pjurczenko** [comment]
What do you think about "terminal errors"?

**Comment by Avasil** [comment]
I'm working on a PR which aims to more or less finalize error handling for `0.1.0` and this matter came back to me

@pjurczenko 
> What do you think about "terminal errors"?

I didn't like it when I first read it because I was too concerned about naming consistency with `raiseError` but now that I'm thinking - it could be pretty good if we go for `BIO#terminate` instead of `BIO#raiseFatalError`. 

Overall naming consistency is pretty big priority to me but I don't think we should worry about it too much in the case of this error channel.

WDYT?

**Comment by alexandru** [comment]
@Avasil not sure what you're thinking of, but "untyped errors" already have a standard and pretty clear name imo — exceptions 🙂

**Comment by Avasil** [comment]
@alexandru 
I feel like having both `raiseError` and `raiseException` or something along these lines could be pretty confusing :D 

In discussions about Bifunctor I often see that errors in Bifunctor IO are called "typed" (reflected in the type signature) and Monofunctor IO has "untyped" errors. 

Of course BIO having all errors represented in the type signature is an illusion and there is also hidden "untyped" error channel which needs at least a small amount of separate combinators. 

The idea is that these unexpected errors are not something the user either cannot handle or can only handle at the edges of the program and it skips most error handling combinators. 

I also extended `Callback` to have `onFatalError` along with `onSuccess` and `onError` and I need to find a proper name for `onFatalError` (or decide to keep that one)

**Comment by pjurczenko** [comment]
@Avasil `BIO#terminate` sounds good to me. It fits really well with that "terminal error" naming. I also like the fact that the names would be similar to the ones in Izumi. This will be less confusing for the end users, especially the ones using Izumi typeclasses with BIO datatype (which will be possible I believe).
