### ISSUE TITLE
Implement flip

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#41]
```scala
final def flip: BIO[A, E]
```

A variant like
```scala
final def flipWith[E1, A1](f: BIO[A, E] => BIO[E1, A1]): BIO[E1, A1]
```

from ZIO would be useful as well, it seems like a common pattern if someone uses `flip`.

If we can come up with a cool example for scaladoc that would be awesome!

**Comment by jewertow** [comment]
I will implement these methods.

**Comment by Avasil** [comment]
@jewertow 
Anything I can help with? 
I'm closing on `0.1.0` (would like to release it in 1-2 weeks) and would like to include it there

**Comment by Executioner1939** [comment]
I will take this one :-)
