### ISSUE TITLE
Implement bimap and provide Bifunctor instance

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#5]
The signature:

```scala
final def bimap[E1, B](f: E => E2, g: A => B): BIO[E1, B]
```

It will need a short scaladoc and tests. 

The implementation could be probably in terms of `redeemWith` or if you'd like to play with internals then it could be similar to `redeem` with custom `StackFrame`.

**Comment by SvenvDam** [comment]
I'd like to pick this one up.
