### ISSUE TITLE
Decide on runSyncUnsafe and runToFuture return types

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#52]
Currently we have 
```scala
final def runSyncUnsafe(timeout: Duration = Duration.Inf)(implicit s: Scheduler, permit: CanBlock): A
```

but there might be some value in returning `Either[E, A]`. 

I'm not sure yet if it should be replaced in this method or there should be a new one but I don't want to forget about it

**Comment by Avasil** [comment]
I guess we can always call `attempt.runSyncUnsafe` so I will leave it like that unless there will be a demand

**Comment by pjurczenko** [comment]
@Avasil One thing that might be worth consideration here is that currently `runSyncUnsafe` behaves differently than `runToFuture` when it comes to materializing typed errors. The former returns a plain `A` value on success and throws `TaskRunLoop$WrappedException` on typed errors, while the latter returns a `CompletableFuture[Either[E, A]]`, thus materializes typed errors into values and doesn't propagate them into the error channel of the `Future`.

What do you think about unifying this somehow? We could either return `Either[E, A]` in `runSyncUnsafe`, or we could return `CompletableFuture[A]` in `runToFuture`.

PS I'm also slightly worried about throwing that `WrappedException` on typed errors during `runSyncUnsafe`. In its current form (i.e. generic name + no stacktrace) it might be misleading to the users.

**Comment by Avasil** [comment]
As I am updating some of the scaladocs to `monix-bio` I'm getting bigger and bigger impression that 

```scala
def runToFuture[E1 >: E](implicit s: Scheduler): CancelableFuture[Either[E1, A]]
```

is very annoying :D And will be even more annoying to use in mixed codebases, e.g. `BIO` + Akka HTTP 

So I'm considering different options:

1. 
```scala
def runToFuture(implicit s: Scheduler, ev: E <:< Throwable): CancelableFuture[A]
```

which should work for `E = Nothing` as well so we can do `attempt.runToFuture` to expose typed error

2.
The same thing `runSyncUnsafe` is doing currently:

```scala
def runToFuture(implicit s: Scheduler): CancelableFuture[A]
```

which transforms `E != Throwable` to `UncaughtErrorException`. 

Or other exception, I chose `UncaughtErrorException` because it was already used in Monix for reporting failures that couldn't be exposed as a result of the `Task`. We could go for something else if the name is not telling much

======

I have similar dillema with `runSyncUnsafe`

I feel like nr 1 looks very good for `runToFuture` but I'm not so sure about `Throwable` requirement for `runSyncUnsafe`

What do you think?

**Comment by Avasil** [comment]
Okay, for `0.1.0` I decided to specialize both `runToFuture` and `runSyncUnsafe` to `Throwable`.

The user has a choice to do `task.attempt.runSyncUnsafe` to receive `Either[E, A]` or `mapError` / `hideErrorsWith` to cast error type to exception.

We'll see if there are any complaints before `1.0.0` :)
