### ISSUE TITLE
Implement rethrow

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#60]
Something like

```scala
final def rethrow[E1 >: E, B](implicit ev: A <:< Either[E1, B]): BIO[E1, B]
```

to go from `BIO[E, Either[E, B]]` to `BIO[E, B]`

Prior art: 
- https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/MonadError.scala#L39 (rethrow)
- https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZIO.scala#L77 (absolve)

**Comment by bszwej** [comment]
I'll work on that
