### ISSUE TITLE
Reimplement `UIO.evalAsync` as a low-level operator

### ISSUE THREAD

**Issue by Avasil** [monix/monix-bio#70]
Currently it's implemented as 
```scala
def evalAsync[A](a: => A): UIO[A] =
  BIO.EvalTotal(a _).executeAsync
```

which is something like `BIO.shift.flatMap(_ => BIO.EvalTotal(a _))`

We could optimize it relatively easily by implementing it in a similar way to [TaskEvalAsync](https://github.com/monix/monix-bio/blob/master/core/shared/src/main/scala/monix/bio/internal/TaskEvalAsync.scala).

The only difference is that we should call `cb.onFatalError(e)` and return `UIO[A]` instead of `Task[A]`

**Comment by Executioner1939** [comment]
I will take this one :-)

**Comment by Executioner1939** [comment]
Nevermind, this one seems done 🤔 🤔 

```scala
  /** Lifts a non-strict value, a thunk, to a `Task` that will trigger a logical
    * fork before evaluation.
    *
    * Like [[eval]], but the provided `thunk` will not be evaluated immediately.
    * Equivalence:
    *
    * `Task.evalAsync(a) <-> Task.eval(a).executeAsync`
    *
    * @param a is the thunk to process on evaluation
    */
  def evalAsync[A](a: => A): Task[A] =
    TaskEvalAsync(a _)
```
